### ISSUE TITLE
How to construct the initial state for a large application?

### ISSUE THREAD

**Issue by kwhitaker** [gajus/canonical-reducer-composition#2]
The answer to this might be self-evident and I'm just missing it, but...

If I have a complex app with many pieces of state to be tracked (dashboard, admin, blog, comments, etc...), what's an effective strategy for building the initial state with CRC?  Vanilla redux encourages me to manage the initial states for those pieces as part of the reducer setup:

```
let initialState = {
  isFetching: false,
  comments: []
}

export function comments(state=initialState, action) {...}
```

This keeps things tidy and "near" the concerns the initial states affect.  It seems like CRC wants me to break those initial states out and construct a large tree elsewhere.

**Comment by gajus** [comment]
@kwhitaker Sorry, did not see the question earlier.

See, https://github.com/gajus/canonical-reducer-composition/issues/1. Please contribute to the discussion. As soon as the consensus is met, I will implement the feature.

**Comment by gajus** [comment]
https://github.com/gajus/canonical-reducer-composition/blob/master/README.md#construct-action-handler
