### ISSUE TITLE
The right approach to split domains

### ISSUE THREAD

**Issue by asaf** [gajus/canonical-reducer-composition#5]
Hey,

According to the spec, it seems like a reducer such below should work,

``` js
let reducers = {
  users: {
    foo: {
      CONSTRUCT: () => {return Immutable.List()}
    }
  },
  bar: {
    CONSTRUCT: () => {return Immutable.List()}
  }
}
```

Apparently, it fails on `Reducer definition object action handler names must be valid action names` on the 'foo' part,

What's the right syntax for having nested domains ?

Thanks.

**Comment by asaf** [comment]
Wrong repo

**Comment by gajus** [comment]
This refers to https://github.com/gajus/canonical-reducer-composition/issues/5.
